[build]
  command = "npm run netlify"
  publish = ".next"
  functions = ".netlify/functions-internal"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200

