[build]
  command = "npm run netlify"
  publish = ".next"
  functions = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Let the Next.js plugin handle all routing automatically

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = ".next"

