[build]
  command = "npm run netlify"
  publish = ".next"
  functions = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

